// IN PROGRESS
export const FETCHING_CLIENT = 'FETCHING_CLIENT';
export const FETCHING_PROFESSIONALS = 'FETCHING_PROFESSIONALS';
export const FETCHING_SERVICES = 'FETCHING_SERVICES';
export const POSTING_SCHEDULE = 'POSTING_SCHEDULE';


// CANCEL
export const CLIENT_FETCH_CANCEL = 'CLIENT_FETCH_CANCEL';
export const PROFESSIONALS_FETCH_CANCEL = 'PROFESSIONALS_FETCH_CANCEL';
export const SERVICES_FETCH_CANCEL = 'SERVICES_FETCH_CANCEL';
export const SCHEDULE_POST_CANCEL = 'SCHEDULE_POST_CANCEL';


// FULFILLED
export const CLIENT_FETCH_FULFILLED = 'CLIENT_FETCH_FULFILLED';
export const PROFESSIONALS_FETCH_FULFILLED = 'PROFESSIONALS_FETCH_FULFILLED';
export const SERVICES_FETCH_FULFILLED = 'SERVICES_FETCH_FULFILLED';
export const SCHEDULE_POST_FULFILLED = 'SCHEDULE_POST_FULFILLED';


// ERROR
export const CLIENT_FETCH_ERROR = 'CLIENT_FETCH_ERROR';
export const PROFESSIONALS_FETCH_ERROR = 'PROFESSIONALS_FETCH_ERROR';
export const SERVICES_FETCH_ERROR = 'SERVICES_FETCH_ERROR';
export const SCHEDULE_POST_ERROR = 'SCHEDULE_POST_ERROR';