export const SCHEDULE_DELETE_PROCESSING = 'SCHEDULE_DELETE_PROCESSING';

export const SCHEDULE_DELETE_CANCEL = 'SCHEDULE_DELETE_CANCEL';

export const SCHEDULE_DELETE_FULFILLED = 'SCHEDULE_DELETE_FULFILLED';

export const SCHEDULE_DELETE_ERROR = 'SCHEDULE_DELETE_ERROR';

